import {ReactNode} from "react";
import Head from "next/head";
import Header from "./Header/Header";

const Layout = (
    {
        children,
        title
    }:{
        children: ReactNode,
        title: string
    }
) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>

            {children}

        </>
    )
}

export default Layout